interface question {
    Id: number;
    QuestionId: string;
    QuestionText: string;
    QuestionPrompt: string;
    QuestionAltA: string;
    QuestionAltB: string;
    QuestionAltC: string;
    QuestionAltD: string;
    QuestionAltE: string;
    CorrectAlternative: string;
    SubjectId: number;
    TopicId: number;
    SubTopicId: number;
}
const questionsTest: question[] = [
  // Mathematics - Algebra
  {
    Id: 1,
    QuestionId: "Q001",
    QuestionText: "What is the value of x in the equation 2x + 5 = 15?",
    QuestionPrompt: "Solve for x:",
    QuestionAltA: "3",
    QuestionAltB: "5",
    QuestionAltC: "7",
    QuestionAltD: "10",
    QuestionAltE: "12",
    CorrectAlternative: "B",
    SubjectId: 1,
    TopicId: 1,
    SubTopicId: 1,
  },
  {
    Id: 2,
    QuestionId: "Q002",
    QuestionText: "Which of the following is a quadratic equation?",
    QuestionPrompt: "Identify the quadratic equation:",
    QuestionAltA: "3x + 2 = 0",
    QuestionAltB: "x² + 3x + 2 = 0",
    QuestionAltC: "x³ - 1 = 0",
    QuestionAltD: "2x = 8",
    QuestionAltE: "√x = 4",
    CorrectAlternative: "B",
    SubjectId: 1,
    TopicId: 1,
    SubTopicId: 2,
  },
  {
    Id: 3,
    QuestionId: "Q003",
    QuestionText: "What is the slope of the line y = 3x - 7?",
    QuestionPrompt: "Find the slope:",
    QuestionAltA: "-7",
    QuestionAltB: "7",
    QuestionAltC: "3",
    QuestionAltD: "-3",
    QuestionAltE: "1/3",
    CorrectAlternative: "C",
    SubjectId: 1,
    TopicId: 1,
    SubTopicId: 3,
  },
  {
    Id: 4,
    QuestionId: "Q004",
    QuestionText: "What is the result of (x + 3)(x - 3)?",
    QuestionPrompt: "Expand the expression:",
    QuestionAltA: "x² + 9",
    QuestionAltB: "x² - 9",
    QuestionAltC: "x² + 6x - 9",
    QuestionAltD: "x² - 6x + 9",
    QuestionAltE: "x² + 6x + 9",
    CorrectAlternative: "B",
    SubjectId: 1,
    TopicId: 1,
    SubTopicId: 2,
  },
  {
    Id: 5,
    QuestionId: "Q005",
    QuestionText: "If f(x) = 2x² - 4x + 1, what is f(3)?",
    QuestionPrompt: "Evaluate the function:",
    QuestionAltA: "5",
    QuestionAltB: "7",
    QuestionAltC: "10",
    QuestionAltD: "7",
    QuestionAltE: "7",
    CorrectAlternative: "B",
    SubjectId: 1,
    TopicId: 1,
    SubTopicId: 4,
  },

  // Mathematics - Geometry
  {
    Id: 6,
    QuestionId: "Q006",
    QuestionText: "What is the area of a circle with radius 5?",
    QuestionPrompt: "Calculate the area (use π ≈ 3.14):",
    QuestionAltA: "15.7",
    QuestionAltB: "31.4",
    QuestionAltC: "78.5",
    QuestionAltD: "314",
    QuestionAltE: "25π²",
    CorrectAlternative: "C",
    SubjectId: 1,
    TopicId: 2,
    SubTopicId: 5,
  },
  {
    Id: 7,
    QuestionId: "Q007",
    QuestionText: "How many degrees are in the interior angles of a triangle?",
    QuestionPrompt: "Sum of interior angles:",
    QuestionAltA: "90°",
    QuestionAltB: "270°",
    QuestionAltC: "360°",
    QuestionAltD: "180°",
    QuestionAltE: "120°",
    CorrectAlternative: "D",
    SubjectId: 1,
    TopicId: 2,
    SubTopicId: 6,
  },
  {
    Id: 8,
    QuestionId: "Q008",
    QuestionText: "What is the Pythagorean theorem?",
    QuestionPrompt: "Select the correct formula:",
    QuestionAltA: "a + b = c",
    QuestionAltB: "a² - b² = c²",
    QuestionAltC: "a² + b² = c²",
    QuestionAltD: "(a + b)² = c",
    QuestionAltE: "a × b = c²",
    CorrectAlternative: "C",
    SubjectId: 1,
    TopicId: 2,
    SubTopicId: 7,
  },
  {
    Id: 9,
    QuestionId: "Q009",
    QuestionText: "What is the volume of a cube with side length 4?",
    QuestionPrompt: "Calculate the volume:",
    QuestionAltA: "12",
    QuestionAltB: "16",
    QuestionAltC: "48",
    QuestionAltD: "64",
    QuestionAltE: "96",
    CorrectAlternative: "D",
    SubjectId: 1,
    TopicId: 2,
    SubTopicId: 8,
  },
  {
    Id: 10,
    QuestionId: "Q010",
    QuestionText: "What is the perimeter of a rectangle with width 4 and length 7?",
    QuestionPrompt: "Calculate the perimeter:",
    QuestionAltA: "11",
    QuestionAltB: "22",
    QuestionAltC: "28",
    QuestionAltD: "18",
    QuestionAltE: "24",
    CorrectAlternative: "B",
    SubjectId: 1,
    TopicId: 2,
    SubTopicId: 5,
  },

  // Mathematics - Statistics
  {
    Id: 11,
    QuestionId: "Q011",
    QuestionText: "What is the mean of the dataset: 4, 8, 6, 5, 3, 2, 8, 9, 2, 5?",
    QuestionPrompt: "Calculate the arithmetic mean:",
    QuestionAltA: "4.5",
    QuestionAltB: "5",
    QuestionAltC: "5.2",
    QuestionAltD: "6",
    QuestionAltE: "5.5",
    CorrectAlternative: "C",
    SubjectId: 1,
    TopicId: 3,
    SubTopicId: 9,
  },
  {
    Id: 12,
    QuestionId: "Q012",
    QuestionText: "What is the median of: 3, 7, 1, 9, 4?",
    QuestionPrompt: "Find the median:",
    QuestionAltA: "1",
    QuestionAltB: "3",
    QuestionAltC: "4",
    QuestionAltD: "7",
    QuestionAltE: "9",
    CorrectAlternative: "C",
    SubjectId: 1,
    TopicId: 3,
    SubTopicId: 9,
  },
  {
    Id: 13,
    QuestionId: "Q013",
    QuestionText: "If a die is rolled once, what is the probability of rolling a 4?",
    QuestionPrompt: "Calculate the probability:",
    QuestionAltA: "1/3",
    QuestionAltB: "1/4",
    QuestionAltC: "1/6",
    QuestionAltD: "4/6",
    QuestionAltE: "1/2",
    CorrectAlternative: "C",
    SubjectId: 1,
    TopicId: 3,
    SubTopicId: 10,
  },

  // Science - Biology
  {
    Id: 14,
    QuestionId: "Q014",
    QuestionText: "What is the powerhouse of the cell?",
    QuestionPrompt: "Identify the organelle:",
    QuestionAltA: "Nucleus",
    QuestionAltB: "Ribosome",
    QuestionAltC: "Endoplasmic Reticulum",
    QuestionAltD: "Mitochondria",
    QuestionAltE: "Golgi Apparatus",
    CorrectAlternative: "D",
    SubjectId: 2,
    TopicId: 4,
    SubTopicId: 11,
  },
  {
    Id: 15,
    QuestionId: "Q015",
    QuestionText: "Which molecule carries genetic information in most living organisms?",
    QuestionPrompt: "Identify the molecule:",
    QuestionAltA: "RNA",
    QuestionAltB: "ATP",
    QuestionAltC: "DNA",
    QuestionAltD: "Protein",
    QuestionAltE: "Lipid",
    CorrectAlternative: "C",
    SubjectId: 2,
    TopicId: 4,
    SubTopicId: 12,
  },
  {
    Id: 16,
    QuestionId: "Q016",
    QuestionText: "How many chromosomes does a typical human cell have?",
    QuestionPrompt: "Select the correct number:",
    QuestionAltA: "23",
    QuestionAltB: "44",
    QuestionAltC: "46",
    QuestionAltD: "48",
    QuestionAltE: "92",
    CorrectAlternative: "C",
    SubjectId: 2,
    TopicId: 4,
    SubTopicId: 12,
  },
  {
    Id: 17,
    QuestionId: "Q017",
    QuestionText: "What is the process by which plants make food using sunlight?",
    QuestionPrompt: "Name the process:",
    QuestionAltA: "Respiration",
    QuestionAltB: "Photosynthesis",
    QuestionAltC: "Fermentation",
    QuestionAltD: "Transpiration",
    QuestionAltE: "Osmosis",
    CorrectAlternative: "B",
    SubjectId: 2,
    TopicId: 4,
    SubTopicId: 13,
  },
  {
    Id: 18,
    QuestionId: "Q018",
    QuestionText: "Which blood type is considered the universal donor?",
    QuestionPrompt: "Identify the universal donor blood type:",
    QuestionAltA: "A",
    QuestionAltB: "B",
    QuestionAltC: "AB",
    QuestionAltD: "O",
    QuestionAltE: "O+",
    CorrectAlternative: "D",
    SubjectId: 2,
    TopicId: 4,
    SubTopicId: 14,
  },
  {
    Id: 19,
    QuestionId: "Q019",
    QuestionText: "What is the basic unit of life?",
    QuestionPrompt: "Select the correct answer:",
    QuestionAltA: "Atom",
    QuestionAltB: "Molecule",
    QuestionAltC: "Organ",
    QuestionAltD: "Cell",
    QuestionAltE: "Tissue",
    CorrectAlternative: "D",
    SubjectId: 2,
    TopicId: 4,
    SubTopicId: 11,
  },
  {
    Id: 20,
    QuestionId: "Q020",
    QuestionText: "Which organ is responsible for filtering blood in the human body?",
    QuestionPrompt: "Identify the organ:",
    QuestionAltA: "Liver",
    QuestionAltB: "Heart",
    QuestionAltC: "Lungs",
    QuestionAltD: "Spleen",
    QuestionAltE: "Kidney",
    CorrectAlternative: "E",
    SubjectId: 2,
    TopicId: 4,
    SubTopicId: 14,
  },

  // Science - Chemistry
  {
    Id: 21,
    QuestionId: "Q021",
    QuestionText: "What is the chemical formula for water?",
    QuestionPrompt: "Select the correct formula:",
    QuestionAltA: "HO",
    QuestionAltB: "H2O",
    QuestionAltC: "H2O2",
    QuestionAltD: "OH2",
    QuestionAltE: "H3O",
    CorrectAlternative: "B",
    SubjectId: 2,
    TopicId: 5,
    SubTopicId: 15,
  },
  {
    Id: 22,
    QuestionId: "Q022",
    QuestionText: "What is the atomic number of Carbon?",
    QuestionPrompt: "Identify the atomic number:",
    QuestionAltA: "4",
    QuestionAltB: "6",
    QuestionAltC: "8",
    QuestionAltD: "12",
    QuestionAltE: "14",
    CorrectAlternative: "B",
    SubjectId: 2,
    TopicId: 5,
    SubTopicId: 16,
  },
  {
    Id: 23,
    QuestionId: "Q023",
    QuestionText: "Which element has the symbol 'Au'?",
    QuestionPrompt: "Identify the element:",
    QuestionAltA: "Silver",
    QuestionAltB: "Aluminum",
    QuestionAltC: "Gold",
    QuestionAltD: "Copper",
    QuestionAltE: "Iron",
    CorrectAlternative: "C",
    SubjectId: 2,
    TopicId: 5,
    SubTopicId: 16,
  },
  {
    Id: 24,
    QuestionId: "Q024",
    QuestionText: "What is the pH of a neutral solution?",
    QuestionPrompt: "Select the correct pH value:",
    QuestionAltA: "0",
    QuestionAltB: "5",
    QuestionAltC: "7",
    QuestionAltD: "10",
    QuestionAltE: "14",
    CorrectAlternative: "C",
    SubjectId: 2,
    TopicId: 5,
    SubTopicId: 17,
  },
  {
    Id: 25,
    QuestionId: "Q025",
    QuestionText: "What type of bond involves the sharing of electron pairs?",
    QuestionPrompt: "Identify the bond type:",
    QuestionAltA: "Ionic bond",
    QuestionAltB: "Hydrogen bond",
    QuestionAltC: "Metallic bond",
    QuestionAltD: "Covalent bond",
    QuestionAltE: "Van der Waals bond",
    CorrectAlternative: "D",
    SubjectId: 2,
    TopicId: 5,
    SubTopicId: 18,
  },

  // Science - Physics
  {
    Id: 26,
    QuestionId: "Q026",
    QuestionText: "What is Newton's second law of motion?",
    QuestionPrompt: "Select the correct formula:",
    QuestionAltA: "F = mv",
    QuestionAltB: "F = ma",
    QuestionAltC: "E = mc²",
    QuestionAltD: "P = mv",
    QuestionAltE: "W = Fd",
    CorrectAlternative: "B",
    SubjectId: 2,
    TopicId: 6,
    SubTopicId: 19,
  },
  {
    Id: 27,
    QuestionId: "Q027",
    QuestionText: "What is the speed of light in a vacuum?",
    QuestionPrompt: "Identify the correct value:",
    QuestionAltA: "3 × 10⁶ m/s",
    QuestionAltB: "3 × 10⁷ m/s",
    QuestionAltC: "3 × 10⁸ m/s",
    QuestionAltD: "3 × 10⁹ m/s",
    QuestionAltE: "3 × 10¹⁰ m/s",
    CorrectAlternative: "C",
    SubjectId: 2,
    TopicId: 6,
    SubTopicId: 20,
  },
  {
    Id: 28,
    QuestionId: "Q028",
    QuestionText: "Which of the following is a unit of energy?",
    QuestionPrompt: "Select the energy unit:",
    QuestionAltA: "Newton",
    QuestionAltB: "Pascal",
    QuestionAltC: "Watt",
    QuestionAltD: "Joule",
    QuestionAltE: "Ampere",
    CorrectAlternative: "D",
    SubjectId: 2,
    TopicId: 6,
    SubTopicId: 21,
  },
  {
    Id: 29,
    QuestionId: "Q029",
    QuestionText: "What is the SI unit of electric current?",
    QuestionPrompt: "Identify the unit:",
    QuestionAltA: "Volt",
    QuestionAltB: "Ohm",
    QuestionAltC: "Watt",
    QuestionAltD: "Coulomb",
    QuestionAltE: "Ampere",
    CorrectAlternative: "E",
    SubjectId: 2,
    TopicId: 6,
    SubTopicId: 22,
  },
  {
    Id: 30,
    QuestionId: "Q030",
    QuestionText: "Which law states that for every action there is an equal and opposite reaction?",
    QuestionPrompt: "Identify the law:",
    QuestionAltA: "Newton's First Law",
    QuestionAltB: "Newton's Second Law",
    QuestionAltC: "Newton's Third Law",
    QuestionAltD: "Law of Conservation of Energy",
    QuestionAltE: "Hooke's Law",
    CorrectAlternative: "C",
    SubjectId: 2,
    TopicId: 6,
    SubTopicId: 19,
  },

  // History
  {
    Id: 31,
    QuestionId: "Q031",
    QuestionText: "In which year did World War II end?",
    QuestionPrompt: "Select the correct year:",
    QuestionAltA: "1943",
    QuestionAltB: "1944",
    QuestionAltC: "1945",
    QuestionAltD: "1946",
    QuestionAltE: "1947",
    CorrectAlternative: "C",
    SubjectId: 3,
    TopicId: 7,
    SubTopicId: 23,
  },
  {
    Id: 32,
    QuestionId: "Q032",
    QuestionText: "Who was the first President of the United States?",
    QuestionPrompt: "Identify the person:",
    QuestionAltA: "Thomas Jefferson",
    QuestionAltB: "John Adams",
    QuestionAltC: "Benjamin Franklin",
    QuestionAltD: "George Washington",
    QuestionAltE: "Abraham Lincoln",
    CorrectAlternative: "D",
    SubjectId: 3,
    TopicId: 7,
    SubTopicId: 24,
  },
  {
    Id: 33,
    QuestionId: "Q033",
    QuestionText: "The French Revolution began in which year?",
    QuestionPrompt: "Select the correct year:",
    QuestionAltA: "1776",
    QuestionAltB: "1789",
    QuestionAltC: "1800",
    QuestionAltD: "1815",
    QuestionAltE: "1750",
    CorrectAlternative: "B",
    SubjectId: 3,
    TopicId: 7,
    SubTopicId: 25,
  },
  {
    Id: 34,
    QuestionId: "Q034",
    QuestionText: "Who was the leader of Nazi Germany during World War II?",
    QuestionPrompt: "Identify the leader:",
    QuestionAltA: "Mussolini",
    QuestionAltB: "Stalin",
    QuestionAltC: "Hitler",
    QuestionAltD: "Franco",
    QuestionAltE: "Hirohito",
    CorrectAlternative: "C",
    SubjectId: 3,
    TopicId: 7,
    SubTopicId: 23,
  },
  {
    Id: 35,
    QuestionId: "Q035",
    QuestionText: "Which empire was known as the 'Empire on which the sun never sets'?",
    QuestionPrompt: "Identify the empire:",
    QuestionAltA: "Roman Empire",
    QuestionAltB: "Ottoman Empire",
    QuestionAltC: "Mongol Empire",
    QuestionAltD: "British Empire",
    QuestionAltE: "Spanish Empire",
    CorrectAlternative: "D",
    SubjectId: 3,
    TopicId: 7,
    SubTopicId: 26,
  },
  {
    Id: 36,
    QuestionId: "Q036",
    QuestionText: "The Berlin Wall fell in which year?",
    QuestionPrompt: "Select the correct year:",
    QuestionAltA: "1985",
    QuestionAltB: "1987",
    QuestionAltC: "1989",
    QuestionAltD: "1991",
    QuestionAltE: "1993",
    CorrectAlternative: "C",
    SubjectId: 3,
    TopicId: 7,
    SubTopicId: 27,
  },
  {
    Id: 37,
    QuestionId: "Q037",
    QuestionText: "Which ancient wonder was located in Alexandria, Egypt?",
    QuestionPrompt: "Identify the wonder:",
    QuestionAltA: "Colossus of Rhodes",
    QuestionAltB: "Hanging Gardens of Babylon",
    QuestionAltC: "Lighthouse of Alexandria",
    QuestionAltD: "Temple of Artemis",
    QuestionAltE: "Statue of Zeus",
    CorrectAlternative: "C",
    SubjectId: 3,
    TopicId: 7,
    SubTopicId: 28,
  },

  // Geography
  {
    Id: 38,
    QuestionId: "Q038",
    QuestionText: "What is the largest continent by area?",
    QuestionPrompt: "Identify the continent:",
    QuestionAltA: "Africa",
    QuestionAltB: "North America",
    QuestionAltC: "Europe",
    QuestionAltD: "Asia",
    QuestionAltE: "South America",
    CorrectAlternative: "D",
    SubjectId: 3,
    TopicId: 8,
    SubTopicId: 29,
  },
  {
    Id: 39,
    QuestionId: "Q039",
    QuestionText: "What is the capital of Australia?",
    QuestionPrompt: "Identify the capital city:",
    QuestionAltA: "Sydney",
    QuestionAltB: "Melbourne",
    QuestionAltC: "Brisbane",
    QuestionAltD: "Perth",
    QuestionAltE: "Canberra",
    CorrectAlternative: "E",
    SubjectId: 3,
    TopicId: 8,
    SubTopicId: 30,
  },
  {
    Id: 40,
    QuestionId: "Q040",
    QuestionText: "Which river is the longest in the world?",
    QuestionPrompt: "Identify the river:",
    QuestionAltA: "Amazon",
    QuestionAltB: "Nile",
    QuestionAltC: "Yangtze",
    QuestionAltD: "Mississippi",
    QuestionAltE: "Congo",
    CorrectAlternative: "B",
    SubjectId: 3,
    TopicId: 8,
    SubTopicId: 31,
  },
  {
    Id: 41,
    QuestionId: "Q041",
    QuestionText: "How many countries are there in Africa?",
    QuestionPrompt: "Select the correct number:",
    QuestionAltA: "44",
    QuestionAltB: "48",
    QuestionAltC: "54",
    QuestionAltD: "58",
    QuestionAltE: "62",
    CorrectAlternative: "C",
    SubjectId: 3,
    TopicId: 8,
    SubTopicId: 29,
  },
  {
    Id: 42,
    QuestionId: "Q042",
    QuestionText: "What is the smallest country in the world?",
    QuestionPrompt: "Identify the country:",
    QuestionAltA: "Monaco",
    QuestionAltB: "San Marino",
    QuestionAltC: "Liechtenstein",
    QuestionAltD: "Vatican City",
    QuestionAltE: "Maldives",
    CorrectAlternative: "D",
    SubjectId: 3,
    TopicId: 8,
    SubTopicId: 30,
  },

  // Literature
  {
    Id: 43,
    QuestionId: "Q043",
    QuestionText: "Who wrote 'Romeo and Juliet'?",
    QuestionPrompt: "Identify the author:",
    QuestionAltA: "Charles Dickens",
    QuestionAltB: "Jane Austen",
    QuestionAltC: "William Shakespeare",
    QuestionAltD: "Mark Twain",
    QuestionAltE: "Leo Tolstoy",
    CorrectAlternative: "C",
    SubjectId: 4,
    TopicId: 9,
    SubTopicId: 32,
  },
  {
    Id: 44,
    QuestionId: "Q044",
    QuestionText: "In which novel does the character Holden Caulfield appear?",
    QuestionPrompt: "Identify the novel:",
    QuestionAltA: "The Great Gatsby",
    QuestionAltB: "To Kill a Mockingbird",
    QuestionAltC: "The Catcher in the Rye",
    QuestionAltD: "Of Mice and Men",
    QuestionAltE: "Lord of the Flies",
    CorrectAlternative: "C",
    SubjectId: 4,
    TopicId: 9,
    SubTopicId: 33,
  },
  {
    Id: 45,
    QuestionId: "Q045",
    QuestionText: "Who wrote '1984'?",
    QuestionPrompt: "Identify the author:",
    QuestionAltA: "Aldous Huxley",
    QuestionAltB: "George Orwell",
    QuestionAltC: "Ray Bradbury",
    QuestionAltD: "H.G. Wells",
    QuestionAltE: "Isaac Asimov",
    CorrectAlternative: "B",
    SubjectId: 4,
    TopicId: 9,
    SubTopicId: 33,
  },
  {
    Id: 46,
    QuestionId: "Q046",
    QuestionText: "What literary device involves giving human traits to non-human things?",
    QuestionPrompt: "Identify the device:",
    QuestionAltA: "Simile",
    QuestionAltB: "Metaphor",
    QuestionAltC: "Personification",
    QuestionAltD: "Alliteration",
    QuestionAltE: "Hyperbole",
    CorrectAlternative: "C",
    SubjectId: 4,
    TopicId: 9,
    SubTopicId: 34,
  },
  {
    Id: 47,
    QuestionId: "Q047",
    QuestionText: "Which Shakespeare play features the character Hamlet?",
    QuestionPrompt: "Identify the play:",
    QuestionAltA: "Macbeth",
    QuestionAltB: "King Lear",
    QuestionAltC: "Othello",
    QuestionAltD: "Hamlet",
    QuestionAltE: "The Tempest",
    CorrectAlternative: "D",
    SubjectId: 4,
    TopicId: 9,
    SubTopicId: 32,
  }]

export default questionsTest;

